//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.22 at 12:30:59 AM CEST 
//


package taeds;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the taedsBook package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class BookObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: taedsBook
     * 
     */
    public BookObjectFactory() {
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO }
     * 
     */
    public PETICIONCERTIFICADO createPETICIONCERTIFICADO() {
        return new PETICIONCERTIFICADO();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.DATOS }
     * 
     */
    public PETICIONCERTIFICADO.DATOS createPETICIONCERTIFICADODATOS() {
        return new PETICIONCERTIFICADO.DATOS();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.DATOS.ASEGURADOS }
     * 
     */
    public PETICIONCERTIFICADO.DATOS.ASEGURADOS createPETICIONCERTIFICADODATOSASEGURADOS() {
        return new PETICIONCERTIFICADO.DATOS.ASEGURADOS();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.MODALIDAD }
     * 
     */
    public PETICIONCERTIFICADO.MODALIDAD createPETICIONCERTIFICADOMODALIDAD() {
        return new PETICIONCERTIFICADO.MODALIDAD();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO }
     * 
     */
    public PETICIONCERTIFICADO.MODALIDAD.DESTINO createPETICIONCERTIFICADOMODALIDADDESTINO() {
        return new PETICIONCERTIFICADO.MODALIDAD.DESTINO();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.AUTENTICACION }
     * 
     */
    public PETICIONCERTIFICADO.AUTENTICACION createPETICIONCERTIFICADOAUTENTICACION() {
        return new PETICIONCERTIFICADO.AUTENTICACION();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO }
     * 
     */
    public PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO createPETICIONCERTIFICADODATOSASEGURADOSASEGURADO() {
        return new PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO();
    }

    /**
     * Create an instance of {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION }
     * 
     */
    public PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION createPETICIONCERTIFICADOMODALIDADDESTINODURACION() {
        return new PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION();
    }

}
