//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.22 at 12:30:59 AM CEST 
//


package taeds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AUTENTICACION">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="login" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MODALIDAD">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DESTINO">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DURACION">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DATOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FECHA_INICIO_VIAJE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NASEGURADOS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ASEGURADOS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ASEGURADO" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PRECIO_NETO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="REF_AGENCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TRAMITADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="COUNTRY_SOLD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "autenticacion",
    "modalidad",
    "datos"
})
@XmlRootElement(name = "PETICION_CERTIFICADO")
public class PETICIONCERTIFICADO {

    @XmlElement(name = "AUTENTICACION", required = true)
    protected PETICIONCERTIFICADO.AUTENTICACION autenticacion;
    @XmlElement(name = "MODALIDAD", required = true)
    protected PETICIONCERTIFICADO.MODALIDAD modalidad;
    @XmlElement(name = "DATOS", required = true)
    protected PETICIONCERTIFICADO.DATOS datos;

    /**
     * Gets the value of the autenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link PETICIONCERTIFICADO.AUTENTICACION }
     *     
     */
    public PETICIONCERTIFICADO.AUTENTICACION getAUTENTICACION() {
        return autenticacion;
    }

    /**
     * Sets the value of the autenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PETICIONCERTIFICADO.AUTENTICACION }
     *     
     */
    public void setAUTENTICACION(PETICIONCERTIFICADO.AUTENTICACION value) {
        this.autenticacion = value;
    }

    /**
     * Gets the value of the modalidad property.
     * 
     * @return
     *     possible object is
     *     {@link PETICIONCERTIFICADO.MODALIDAD }
     *     
     */
    public PETICIONCERTIFICADO.MODALIDAD getMODALIDAD() {
        return modalidad;
    }

    /**
     * Sets the value of the modalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link PETICIONCERTIFICADO.MODALIDAD }
     *     
     */
    public void setMODALIDAD(PETICIONCERTIFICADO.MODALIDAD value) {
        this.modalidad = value;
    }

    /**
     * Gets the value of the datos property.
     * 
     * @return
     *     possible object is
     *     {@link PETICIONCERTIFICADO.DATOS }
     *     
     */
    public PETICIONCERTIFICADO.DATOS getDATOS() {
        return datos;
    }

    /**
     * Sets the value of the datos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PETICIONCERTIFICADO.DATOS }
     *     
     */
    public void setDATOS(PETICIONCERTIFICADO.DATOS value) {
        this.datos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="login" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pass" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cliente" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AUTENTICACION {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "login")
        protected String login;
        @XmlAttribute(name = "pass")
        protected String pass;
        @XmlAttribute(name = "cliente")
        protected String cliente;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the login property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogin() {
            return login;
        }

        /**
         * Sets the value of the login property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogin(String value) {
            this.login = value;
        }

        /**
         * Gets the value of the pass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPass() {
            return pass;
        }

        /**
         * Sets the value of the pass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPass(String value) {
            this.pass = value;
        }

        /**
         * Gets the value of the cliente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCliente() {
            return cliente;
        }

        /**
         * Sets the value of the cliente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCliente(String value) {
            this.cliente = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FECHA_INICIO_VIAJE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NASEGURADOS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ASEGURADOS">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ASEGURADO" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PRECIO_NETO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="REF_AGENCIA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TRAMITADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="COUNTRY_SOLD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fechainicioviaje",
        "nasegurados",
        "asegurados",
        "localidad",
        "precioneto",
        "refagencia",
        "tramitado",
        "countrysold"
    })
    public static class DATOS {

        @XmlElement(name = "FECHA_INICIO_VIAJE", required = true)
        protected String fechainicioviaje;
        @XmlElement(name = "NASEGURADOS")
        protected byte nasegurados;
        @XmlElement(name = "ASEGURADOS", required = true)
        protected PETICIONCERTIFICADO.DATOS.ASEGURADOS asegurados;
        @XmlElement(name = "LOCALIDAD", required = true)
        protected String localidad;
        @XmlElement(name = "PRECIO_NETO", required = true)
        protected String precioneto;
        @XmlElement(name = "REF_AGENCIA", required = true)
        protected String refagencia;
        @XmlElement(name = "TRAMITADO", required = true)
        protected String tramitado;
        @XmlElement(name = "COUNTRY_SOLD", required = true)
        protected String countrysold;

        /**
         * Gets the value of the fechainicioviaje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFECHAINICIOVIAJE() {
            return fechainicioviaje;
        }

        /**
         * Sets the value of the fechainicioviaje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFECHAINICIOVIAJE(String value) {
            this.fechainicioviaje = value;
        }

        /**
         * Gets the value of the nasegurados property.
         * 
         */
        public byte getNASEGURADOS() {
            return nasegurados;
        }

        /**
         * Sets the value of the nasegurados property.
         * 
         */
        public void setNASEGURADOS(byte value) {
            this.nasegurados = value;
        }

        /**
         * Gets the value of the asegurados property.
         * 
         * @return
         *     possible object is
         *     {@link PETICIONCERTIFICADO.DATOS.ASEGURADOS }
         *     
         */
        public PETICIONCERTIFICADO.DATOS.ASEGURADOS getASEGURADOS() {
            return asegurados;
        }

        /**
         * Sets the value of the asegurados property.
         * 
         * @param value
         *     allowed object is
         *     {@link PETICIONCERTIFICADO.DATOS.ASEGURADOS }
         *     
         */
        public void setASEGURADOS(PETICIONCERTIFICADO.DATOS.ASEGURADOS value) {
            this.asegurados = value;
        }

        /**
         * Gets the value of the localidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLOCALIDAD() {
            return localidad;
        }

        /**
         * Sets the value of the localidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLOCALIDAD(String value) {
            this.localidad = value;
        }

        /**
         * Gets the value of the precioneto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRECIONETO() {
            return precioneto;
        }

        /**
         * Sets the value of the precioneto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRECIONETO(String value) {
            this.precioneto = value;
        }

        /**
         * Gets the value of the refagencia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREFAGENCIA() {
            return refagencia;
        }

        /**
         * Sets the value of the refagencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREFAGENCIA(String value) {
            this.refagencia = value;
        }

        /**
         * Gets the value of the tramitado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTRAMITADO() {
            return tramitado;
        }

        /**
         * Sets the value of the tramitado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTRAMITADO(String value) {
            this.tramitado = value;
        }

        /**
         * Gets the value of the countrysold property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOUNTRYSOLD() {
            return countrysold;
        }

        /**
         * Sets the value of the countrysold property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOUNTRYSOLD(String value) {
            this.countrysold = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ASEGURADO" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "asegurado"
        })
        public static class ASEGURADOS {

            @XmlElement(name = "ASEGURADO")
            protected List<PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO> asegurado;

            /**
             * Gets the value of the asegurado property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the asegurado property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getASEGURADO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO }
             * 
             * 
             */
            public List<PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO> getASEGURADO() {
                if (asegurado == null) {
                    asegurado = new ArrayList<PETICIONCERTIFICADO.DATOS.ASEGURADOS.ASEGURADO>();
                }
                return this.asegurado;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nombre"
            })
            public static class ASEGURADO {

                @XmlElement(name = "NOMBRE", required = true)
                protected String nombre;

                /**
                 * Gets the value of the nombre property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNOMBRE() {
                    return nombre;
                }

                /**
                 * Sets the value of the nombre property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNOMBRE(String value) {
                    this.nombre = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DESTINO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DURACION">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destino"
    })
    public static class MODALIDAD {

        @XmlElement(name = "DESTINO", required = true)
        protected PETICIONCERTIFICADO.MODALIDAD.DESTINO destino;
        @XmlAttribute(name = "codigo")
        protected Short codigo;

        /**
         * Gets the value of the destino property.
         * 
         * @return
         *     possible object is
         *     {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO }
         *     
         */
        public PETICIONCERTIFICADO.MODALIDAD.DESTINO getDESTINO() {
            return destino;
        }

        /**
         * Sets the value of the destino property.
         * 
         * @param value
         *     allowed object is
         *     {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO }
         *     
         */
        public void setDESTINO(PETICIONCERTIFICADO.MODALIDAD.DESTINO value) {
            this.destino = value;
        }

        /**
         * Gets the value of the codigo property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setCodigo(Short value) {
            this.codigo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DURACION">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "duracion"
        })
        public static class DESTINO {

            @XmlElement(name = "DURACION", required = true)
            protected PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION duracion;
            @XmlAttribute(name = "codigo")
            protected Byte codigo;

            /**
             * Gets the value of the duracion property.
             * 
             * @return
             *     possible object is
             *     {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION }
             *     
             */
            public PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION getDURACION() {
                return duracion;
            }

            /**
             * Sets the value of the duracion property.
             * 
             * @param value
             *     allowed object is
             *     {@link PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION }
             *     
             */
            public void setDURACION(PETICIONCERTIFICADO.MODALIDAD.DESTINO.DURACION value) {
                this.duracion = value;
            }

            /**
             * Gets the value of the codigo property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setCodigo(Byte value) {
                this.codigo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="codigo" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DURACION {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "codigo")
                protected Byte codigo;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the codigo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getCodigo() {
                    return codigo;
                }

                /**
                 * Sets the value of the codigo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setCodigo(Byte value) {
                    this.codigo = value;
                }

            }

        }

    }

}
